import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";
import Counter from "@/components/Counter";
import UserForm from "@/components/Userform";
import ComponentePai from "@/components/ComponentePai";
import Children from "@/components/Children";
import TaskList from "@/components/TaskList";

export default function Home() {
  return (
    // Fragment - Envolve as tags que contém o conteúdo do site
    <>
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World! Meu primeiro site em React!</h1>
        <Welcome />
        <User />
        {/* Passando props para os components */}
        <Description city="Registro" age={19} email="samia@email.com" />
        {/* Componente com Desestruturação de props */}
        <Pet name="Meias" breed="Preto e branco" age={2}/>
        {/* Componente com Desestruturação de props */}
        <br />
        <Counter />
        <br />
        <UserForm />
        <br />
        <br />
        <ComponentePai />
        <br />
        <br />
        <Children>
          <div>
            <p>Este é o conteudo da Children</p>
          </div>
        </Children>
        <br />
        <br />
        <TaskList 
        tasks={ [
          {
            id: "1",
            text: "Pagar contas",
          },
          {
            id: "2",
            text: "Fazer mercado",
          },
          {
            id: "3",
            text: "Lavar o carro",
          },
          {
            id: "4",
            text: "Estudar react",
          },
        ]}
        />
      </main>      
    </>
  );
}
